import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AdminShell } from "@/components/finora/admin-shell";
import {
  PageHeader,
  StatCard,
  StatusBadge,
  LoadingRows,
  EmptyState,
} from "@/components/finora/primitives";
import { adminListReferrals } from "@/lib/admin.functions";
import { money, dateTime } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/admin/referrals")({
  head: () => ({
    meta: [
      { title: "Referrals — FINORA admin" },
      { name: "description", content: "Referral commissions and top-performing referrers." },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: ReferralsPage,
});

function ReferralsPage() {
  const fn = useServerFn(adminListReferrals);
  const { data, isLoading } = useQuery({ queryKey: ["admin-referrals"], queryFn: () => fn() });

  const commissions = data?.commissions ?? [];
  const total = commissions.reduce((s, c) => s + Number(c.amount), 0);

  return (
    <AdminShell area="referrals">
      <PageHeader
        title="Referrals"
        description="Commission payouts generated by member introductions."
      />

      <div className="mb-6 grid gap-4 sm:grid-cols-3">
        <StatCard label="Commissions paid" value={money(total)} />
        <StatCard label="Commission records" value={commissions.length} />
        <StatCard label="Active referrers" value={data?.topReferrers.length ?? 0} />
      </div>

      {isLoading ? (
        <LoadingRows rows={5} />
      ) : (
        <div className="grid gap-6 lg:grid-cols-[2fr_1fr]">
          <div className="surface-card overflow-x-auto">
            <table className="w-full min-w-[620px] text-sm">
              <thead className="bg-muted/50 text-muted-foreground text-xs uppercase">
                <tr>
                  <th className="px-4 py-3 text-left font-medium">Referrer</th>
                  <th className="px-4 py-3 text-left font-medium">Referred member</th>
                  <th className="px-4 py-3 text-right font-medium">Commission</th>
                  <th className="px-4 py-3 text-center font-medium">Status</th>
                  <th className="px-4 py-3 text-right font-medium">Date</th>
                </tr>
              </thead>
              <tbody className="divide-border/70 divide-y">
                {commissions.map((c) => (
                  <tr key={c.id}>
                    <td className="px-4 py-3">{c.referrer?.full_name || "—"}</td>
                    <td className="px-4 py-3">{c.referred?.full_name || "—"}</td>
                    <td className="num px-4 py-3 text-right">{money(c.amount)}</td>
                    <td className="px-4 py-3 text-center">
                      <StatusBadge status={c.status} />
                    </td>
                    <td className="text-muted-foreground px-4 py-3 text-right text-xs">
                      {dateTime(c.created_at)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {commissions.length === 0 ? <EmptyState title="No commissions yet" /> : null}
          </div>

          <div className="surface-card p-5">
            <h2 className="text-sm font-semibold">Top referrers</h2>
            {data?.topReferrers.length ? (
              <ul className="divide-border/70 mt-3 divide-y text-sm">
                {data.topReferrers.map((r) => (
                  <li key={r.id} className="flex items-center justify-between py-2.5">
                    <div>
                      <p className="font-medium">{r.name || "Unnamed"}</p>
                      <p className="text-muted-foreground text-xs">{r.code}</p>
                    </div>
                    <span className="num font-medium">{r.count}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-muted-foreground mt-3 text-sm">No referrals recorded yet.</p>
            )}
          </div>
        </div>
      )}
    </AdminShell>
  );
}
