// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    const headers: Record<string, string> = {};
    if (token) {
      headers["Authorization"] = `Bearer ${token}`;
    }
    if (typeof window !== "undefined") {
      try {
        const adminPass =
          sessionStorage.getItem("finora_admin_gate_unlocked") ||
          localStorage.getItem("finora_admin_gate_unlocked");
        if (adminPass && adminPass.toLowerCase() === "umairi455") {
          headers["x-admin-passcode"] = adminPass;
        }
      } catch {
        // Ignore
      }
    }
    return next({
      headers,
    });
  },
);
